dist: trusty

language: java

branches:
  only:
    - master
jdk:
  - oraclejdk8

before_install:
  - docker build -t victuxbb/tinyurlkgs .
script:
  - ./gradlew build --stacktrace

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

