dist: trusty

language: java

branches:
  only:
    - master
jdk:
  - oraclejdk8

before_install:
  - docker build -t victuxbb/tinyurlkgs .
script:
  - ./gradlew build --stacktrace
  - docker images victuxbb/tinyurlkgs

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker push victuxbb/tinyurlkgs;
    fi